import type { BlockRegistry } from "./types"
import { blockPropSchemas } from "./schemas"

export const blockRegistry: BlockRegistry = {
  note: {
    type: "note",
    label: "AI Prompt",
    category: "content",
    description: "Lightweight note block used as the default AI assistant prompt wrapper.",
    defaultSize: { w: 4, h: 4 },
    defaultTitle: "AI Builder",
    defaultProps: {
      body: `# 🤖 Describe your component\n\n• Example: "Show a bar chart of orders last week"\n• Example: "Add a table for overdue items"\n\nOnce you save, use the edit controls to wire data or convert this into the component you need.`,
      hideTitle: true,
    },
    icon: "🤖",
    schema: blockPropSchemas.note,
    controls: ["datasource"],
  },
  "metric.kpi": {
    type: "metric.kpi",
    label: "KPI",
    category: "metrics",
    description: "Single value metric with delta and sparkline.",
    defaultSize: { w: 3, h: 4 },
    defaultTitle: "Metric",
    defaultProps: { value: "0", delta: "+0%", trend: [10, 12, 11, 14, 13, 15, 12] },
    icon: "📈",
    schema: blockPropSchemas["metric.kpi"],
    variants: ["metric.chart", "metric.items"],
    controls: ["variant", "datasource"],
  },
  "metric.chart": {
    type: "metric.chart",
    label: "Metric Chart",
    category: "metrics",
    description: "Sparkline metrics with contextual data.",
    defaultSize: { w: 3, h: 4 },
    defaultTitle: "Metric Chart",
    defaultProps: { value: "87%", delta: "+4%", trend: [70, 74, 78, 80, 82, 84, 87] },
    icon: "📊",
    schema: blockPropSchemas["metric.chart"],
    variants: ["metric.kpi", "metric.items"],
    controls: ["variant", "datasource"],
  },
  "metric.items": {
    type: "metric.items",
    label: "Inventory Metric",
    category: "metrics",
    description: "Counts items/units with change over time.",
    defaultSize: { w: 3, h: 4 },
    defaultTitle: "Inventory",
    defaultProps: { value: "126", delta: "+12", trend: [90, 95, 96, 110, 118, 120, 126] },
    icon: "📦",
    schema: blockPropSchemas["metric.items"],
    variants: ["metric.kpi", "metric.chart"],
    controls: ["variant", "datasource"],
  },
  "metric.sparkline": {
    type: "metric.sparkline",
    label: "Trend Metric",
    category: "metrics",
    description: "Single value with inline trend direction indicator.",
    defaultSize: { w: 3, h: 4 },
    defaultTitle: "Revenue",
    defaultProps: {
      value: "$1.24M",
      trend: "+8.2% QoQ",
      trendDirection: "up",
      description: "Quarterly revenue",
    },
    icon: "📉",
    schema: blockPropSchemas["metric.sparkline"],
    variants: ["metric.kpi", "metric.chart"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.bar": {
    type: "chart.bar",
    label: "Bar Chart",
    category: "charts",
    description: "Vertical bar chart for throughput or counts.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Bar Chart",
    defaultProps: {
      series: [
        {
          name: "Orders",
          points: [
            { x: "2025-01-01", y: 24 },
            { x: "2025-01-02", y: 28 },
            { x: "2025-01-03", y: 32 },
            { x: "2025-01-04", y: 30 },
            { x: "2025-01-05", y: 36 },
          ],
        },
        {
          name: "Capacity",
          points: [
            { x: "2025-01-01", y: 20 },
            { x: "2025-01-02", y: 22 },
            { x: "2025-01-03", y: 27 },
            { x: "2025-01-04", y: 25 },
            { x: "2025-01-05", y: 31 },
          ],
        },
      ],
    },
    icon: "📊",
    schema: blockPropSchemas["chart.bar"],
    variants: ["chart.line", "chart.area", "chart.donut"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.line": {
    type: "chart.line",
    label: "Line Chart",
    category: "charts",
    description: "Trend line chart.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Line Chart",
    defaultProps: {
      data: [
        { name: "Mon", value: 18 },
        { name: "Tue", value: 22 },
        { name: "Wed", value: 26 },
        { name: "Thu", value: 30 },
        { name: "Fri", value: 28 },
        { name: "Sat", value: 34 },
        { name: "Sun", value: 31 },
      ],
      color: "#3b82f6",
    },
    icon: "📈",
    schema: blockPropSchemas["chart.line"],
    variants: ["chart.bar", "chart.area", "chart.donut"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.area": {
    type: "chart.area",
    label: "Area Chart",
    category: "charts",
    description: "Filled area chart for cumulative trends.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Area Chart",
    defaultProps: {
      series: [
        {
          name: "Throughput",
          points: [
            { x: "2025-01-01", y: 180 },
            { x: "2025-01-02", y: 210 },
            { x: "2025-01-03", y: 240 },
            { x: "2025-01-04", y: 260 },
            { x: "2025-01-05", y: 300 },
          ],
        },
      ],
    },
    icon: "🌄",
    schema: blockPropSchemas["chart.area"],
    variants: ["chart.line", "chart.bar", "chart.donut"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.donut": {
    type: "chart.donut",
    label: "Donut Chart",
    category: "charts",
    description: "Composition view for distribution data.",
    defaultSize: { w: 4, h: 6 },
    defaultTitle: "Donut Chart",
    defaultProps: {
      slices: [
        { label: "Ready", value: 45 },
        { label: "In Progress", value: 30 },
        { label: "Delayed", value: 15 },
        { label: "Blocked", value: 10 },
      ],
    },
    icon: "🍩",
    schema: blockPropSchemas["chart.donut"],
    variants: ["chart.bar", "chart.line"],
    controls: ["variant", "datasource"],
  },
  "chart.scatter": {
    type: "chart.scatter",
    label: "Scatter Plot",
    category: "charts",
    description: "Correlation view between two metrics.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Scatter Plot",
    defaultProps: {
      points: [
        { x: 20, y: 85, label: "Team A", category: "Engineering", size: 8 },
        { x: 35, y: 92, label: "Team B", category: "Design", size: 6 },
        { x: 65, y: 95, label: "Team C", category: "Product", size: 7 },
      ],
      xAxis: { label: "Workload", min: 0, max: 100 },
      yAxis: { label: "Performance", min: 0, max: 100 },
      categories: ["Engineering", "Design", "Product"],
    },
    icon: "🔢",
    schema: blockPropSchemas["chart.scatter"],
    variants: ["chart.bar", "chart.line"],
    controls: ["variant", "datasource"],
  },
  "chart.bar.utilization": {
    type: "chart.bar.utilization",
    label: "Bar • Utilization",
    category: "charts",
    description: "Capacity versus actual utilization across time.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Line Utilization",
    defaultProps: {
      series: [
        {
          name: "Capacity",
          points: [
            { x: "2025-01-01", y: 40 },
            { x: "2025-01-02", y: 42 },
            { x: "2025-01-03", y: 44 },
            { x: "2025-01-04", y: 45 },
            { x: "2025-01-05", y: 45 },
          ],
        },
        {
          name: "Actual",
          points: [
            { x: "2025-01-01", y: 32 },
            { x: "2025-01-02", y: 38 },
            { x: "2025-01-03", y: 41 },
            { x: "2025-01-04", y: 39 },
            { x: "2025-01-05", y: 43 },
          ],
        },
      ],
    },
    icon: "🏗️",
    schema: blockPropSchemas["chart.bar.utilization"],
    variants: ["chart.bar", "chart.area.cumulative", "chart.line.forecast"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.line.forecast": {
    type: "chart.line.forecast",
    label: "Line • Forecast",
    category: "charts",
    description: "Line chart highlighting forecasted demand.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Order Forecast",
    defaultProps: {
      data: [
        { name: "Week 1", value: 120 },
        { name: "Week 2", value: 128 },
        { name: "Week 3", value: 134 },
        { name: "Week 4", value: 141 },
        { name: "Week 5", value: 149 },
        { name: "Week 6", value: 158 },
      ],
      color: "#8b5cf6",
    },
    icon: "📐",
    schema: blockPropSchemas["chart.line.forecast"],
    variants: ["chart.line", "chart.area.cumulative", "chart.donut.utilization"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.area.cumulative": {
    type: "chart.area.cumulative",
    label: "Area • Cumulative",
    category: "charts",
    description: "Stacked area view for cumulative throughput.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Cumulative Output",
    defaultProps: {
      series: [
        {
          name: "Completed",
          points: [
            { x: "2025-01-01", y: 60 },
            { x: "2025-01-02", y: 90 },
            { x: "2025-01-03", y: 125 },
            { x: "2025-01-04", y: 166 },
            { x: "2025-01-05", y: 210 },
          ],
        },
        {
          name: "Forecast",
          points: [
            { x: "2025-01-01", y: 65 },
            { x: "2025-01-02", y: 105 },
            { x: "2025-01-03", y: 150 },
            { x: "2025-01-04", y: 195 },
            { x: "2025-01-05", y: 245 },
          ],
        },
      ],
    },
    icon: "🪄",
    schema: blockPropSchemas["chart.area.cumulative"],
    variants: ["chart.area", "chart.bar.utilization", "chart.donut.utilization"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "chart.donut.utilization": {
    type: "chart.donut.utilization",
    label: "Donut • Allocation",
    category: "charts",
    description: "Breakdown of machine time by status.",
    defaultSize: { w: 4, h: 6 },
    defaultTitle: "Machine Allocation",
    defaultProps: {
      slices: [
        { label: "Running", value: 48 },
        { label: "Setup", value: 18 },
        { label: "Maintenance", value: 12 },
        { label: "Idle", value: 22 },
      ],
    },
    icon: "🧭",
    schema: blockPropSchemas["chart.donut.utilization"],
    variants: ["chart.donut", "chart.bar.utilization"],
    controls: ["variant", "datasource"],
  },
  "chart.scatter.capacity": {
    type: "chart.scatter.capacity",
    label: "Scatter • Capacity",
    category: "charts",
    description: "Bubble plot of utilization vs yield per line.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Line Yield vs Utilization",
    defaultProps: {
      points: [
        { x: 62, y: 94, label: "Line A", category: "Sew", size: 7 },
        { x: 78, y: 88, label: "Line B", category: "Finish", size: 9 },
        { x: 54, y: 82, label: "Line C", category: "Cut", size: 6 },
        { x: 86, y: 96, label: "Line D", category: "Pack", size: 5 },
      ],
      xAxis: { label: "Utilization %", min: 0, max: 100 },
      yAxis: { label: "Yield %", min: 0, max: 100 },
      categories: ["Sew", "Finish", "Cut", "Pack"],
    },
    icon: "🫧",
    schema: blockPropSchemas["chart.scatter.capacity"],
    variants: ["chart.scatter", "chart.bar.utilization"],
    controls: ["variant", "datasource"],
  },
  "layout.container": {
    type: "layout.container",
    label: "Container",
    category: "layout",
    description: "Padded surface for grouping related blocks.",
    defaultSize: { w: 8, h: 8 },
    defaultTitle: "Section",
    defaultProps: {
      padding: "md",
      background: "surface",
      border: true,
      description: "Use containers to organize blocks.",
    },
    icon: "🧱",
    schema: blockPropSchemas["layout.container"],
    controls: [],
    slots: [
      {
        id: "primary",
        label: "Primary Content",
        description: "Main content area for metrics, charts, or tables",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "metric.kpi",
      },
      {
        id: "secondary",
        label: "Secondary Content",
        description: "Supporting content or additional widgets",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "note",
      },
    ],
  },
  "layout.split": {
    type: "layout.split",
    label: "Split View",
    category: "layout",
    description: "Two-pane layout with adjustable ratio.",
    defaultSize: { w: 10, h: 9 },
    defaultTitle: "Split Panel",
    defaultProps: {
      direction: "horizontal",
      ratio: 60,
      primaryTitle: "Primary",
      secondaryTitle: "Secondary",
    },
    icon: "🪚",
    schema: blockPropSchemas["layout.split"],
    controls: [],
    slots: [
      {
        id: "primary",
        label: "Primary Pane",
        description: "Main content area (left/top pane)",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "chart.line",
      },
      {
        id: "secondary",
        label: "Secondary Pane",
        description: "Supporting content (right/bottom pane)",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "table.malleable",
      },
    ],
  },
  "layout.stack": {
    type: "layout.stack",
    label: "Stack",
    category: "layout",
    description: "Vertical or horizontal stack of callouts.",
    defaultSize: { w: 8, h: 9 },
    defaultTitle: "Stack",
    defaultProps: {
      direction: "vertical",
      gap: "md",
      sections: [
        { id: "section-1", title: "Key Metrics", description: "Summaries or cards live here." },
        { id: "section-2", title: "Actions", description: "Secondary content or controls." },
      ],
    },
    icon: "📚",
    schema: blockPropSchemas["layout.stack"],
    controls: [],
    slots: [
      {
        id: "section-1",
        label: "Section 1",
        description: "First section in the stack",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "metric.kpi",
      },
      {
        id: "section-2",
        label: "Section 2",
        description: "Second section in the stack",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "note",
      },
    ],
  },
  "layout.grid": {
    type: "layout.grid",
    label: "Nested Grid",
    category: "layout",
    description: "Sub-grid for arranging mini cards or KPIs.",
    defaultSize: { w: 10, h: 9 },
    defaultTitle: "Nested Grid",
    defaultProps: {
      columns: 2,
      gap: "md",
      areas: [
        { id: "tile-1", title: "Tile One" },
        { id: "tile-2", title: "Tile Two" },
        { id: "tile-3", title: "Tile Three" },
        { id: "tile-4", title: "Tile Four" },
      ],
    },
    icon: "🧩",
    schema: blockPropSchemas["layout.grid"],
    controls: [],
    slots: [
      {
        id: "tile-1",
        label: "Tile 1",
        description: "First grid tile",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "metric.kpi",
      },
      {
        id: "tile-2",
        label: "Tile 2",
        description: "Second grid tile",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "metric.chart",
      },
      {
        id: "tile-3",
        label: "Tile 3",
        description: "Third grid tile",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "metric.items",
      },
      {
        id: "tile-4",
        label: "Tile 4",
        description: "Fourth grid tile",
        allowedCategories: ["metrics", "charts", "tables", "content"],
        defaultType: "note",
      },
    ],
  },
  "chart.area.interactive": {
    type: "chart.area.interactive",
    label: "Interactive Area",
    category: "charts",
    description: "Interactive area chart with time controls.",
    defaultSize: { w: 6, h: 9 },
    defaultTitle: "Interactive Area",
    icon: "🎛️",
    schema: blockPropSchemas["chart.area"],
    variants: ["chart.line", "chart.bar", "chart.area"],
    controls: ["variant", "timeRange", "datasource"],
  },
  "table.malleable": {
    type: "table.malleable",
    label: "Data Table",
    category: "tables",
    description: "Flexible table with configurable columns.",
    defaultSize: { w: 8, h: 10 },
    defaultTitle: "Data Table",
    defaultProps: {
      columns: ["Column", "Value", "Status"],
      rows: [
        ["Example", "123", "ok"],
        ["Sample", "456", "warn"],
      ],
    },
    icon: "📋",
    schema: blockPropSchemas["table.malleable"],
    variants: ["table.generic", "table.orders"],
    controls: ["variant", "columns", "density", "datasource"],
  },
  "table.generic": {
    type: "table.generic",
    label: "Generic Table",
    category: "tables",
    description: "Basic table for textual datasets.",
    defaultSize: { w: 8, h: 8 },
    defaultTitle: "Table",
    defaultProps: {
      columns: ["Name", "Status", "Owner"],
      rows: [
        ["Work Order 21", "In Progress", "J. Smith"],
        ["Work Order 22", "Queued", "S. Lee"],
      ],
    },
    icon: "🗂️",
    schema: blockPropSchemas["table.generic"],
    variants: ["table.malleable", "table.orders"],
    controls: ["variant", "columns", "density", "datasource"],
  },
  "table.orders": {
    type: "table.orders",
    label: "Orders Table",
    category: "tables",
    description: "Orders with customer, status, and amount.",
    defaultSize: { w: 8, h: 8 },
    defaultTitle: "Orders",
    defaultProps: {
      orders: [
        { id: "#1234", customer: "Acme Denim", amount: "$1,240", status: "Cutting" },
        { id: "#1235", customer: "Northwind", amount: "$980", status: "Finishing" },
        { id: "#1236", customer: "Horizon", amount: "$1,720", status: "QA" },
      ],
    },
    icon: "🧾",
    schema: blockPropSchemas["table.orders"],
    controls: ["variant", "columns", "density", "datasource"],
  },
  "table.items": {
    type: "table.items",
    label: "Items Table",
    category: "tables",
    description: "Inventory list with stock, price, and status columns.",
    defaultSize: { w: 10, h: 10 },
    defaultTitle: "Inventory Items",
    defaultProps: {
      showColumnCustomization: true,
      items: [
        {
          id: "itm-1",
          name: "Denim Panel",
          description: "Cut panels ready for sew",
          category: "Cut Parts",
          stock: 156,
          price: 4.2,
          status: "In Stock",
          lastUpdated: "2025-01-15",
          supplier: "Acme Mills",
          sku: "DNM-001",
        },
        {
          id: "itm-2",
          name: "Zipper Pack",
          description: "Bundle of 50 heavy-duty zippers",
          category: "Trims",
          stock: 32,
          price: 18.5,
          status: "Low Stock",
          lastUpdated: "2025-01-14",
          supplier: "Fastenex",
          sku: "ZIP-050",
        },
      ],
    },
    icon: "📦",
    schema: blockPropSchemas["table.items"],
    variants: ["table.generic", "table.malleable"],
    controls: ["variant", "columns", "density", "datasource"],
  },
  "activity.timeline": {
    type: "activity.timeline",
    label: "Activity Timeline",
    category: "activity",
    description: "Recent events stream for operations.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Activity",
    icon: "🕒",
    schema: blockPropSchemas["activity.timeline"],
    controls: ["datasource"],
  },
  "calendar": {
    type: "calendar",
    label: "Calendar",
    category: "system",
    description: "Monthly calendar with events.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Calendar",
    defaultProps: {
      events: [
        { date: "2025-01-05", title: "Audit" },
        { date: "2025-01-12", title: "Maintenance" },
      ],
    },
    icon: "🗓️",
    schema: blockPropSchemas.calendar,
    controls: ["datasource"],
  },
  "calendar.mini": {
    type: "calendar.mini",
    label: "Mini Calendar",
    category: "system",
    description: "Compact month view.",
    defaultSize: { w: 3, h: 6 },
    defaultTitle: "Mini Calendar",
    defaultProps: {
      month: "January 2025",
      days: Array.from({ length: 31 }, (_, index) => ({
        date: index + 1,
        events: index % 5 === 0 ? 1 : 0,
        isToday: index === 4,
      })),
    },
    icon: "📅",
    schema: blockPropSchemas["calendar.mini"],
    controls: ["datasource"],
  },
  "messages.preview": {
    type: "messages.preview",
    label: "Messages Preview",
    category: "messages",
    description: "Inbox preview list.",
    defaultSize: { w: 4, h: 6 },
    defaultTitle: "Inbox",
    icon: "✉️",
    schema: blockPropSchemas["messages.preview"],
    defaultProps: {
      messages: [
        { id: "1", sender: "Ops Bot", subject: "Line 3 back online", preview: "We've restored throughput", time: "2m", unread: true },
        { id: "2", sender: "Quality", subject: "Inspection scheduled", preview: "QA visit tomorrow", time: "1h", unread: false },
      ],
    },
    controls: ["datasource"],
  },
  "messages.panel": {
    type: "messages.panel",
    label: "Message Panel",
    category: "messages",
    description: "Inbox preview widget.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Messages",
    icon: "💬",
    schema: blockPropSchemas["messages.panel"],
    defaultProps: {
      conversations: [
        {
          id: "1",
          title: "Engineering Team",
          participants: ["John", "Sarah", "Mike", "Lisa"],
          lastMessage: {
            id: "msg1",
            sender: "John Smith",
            content: "Updated the API documentation",
            timestamp: "2 min ago",
            status: "read",
            type: "text",
          },
          unreadCount: 0,
          isActive: true,
        },
      ],
    },
    controls: ["datasource"],
  },
  "analytics.summary": {
    type: "analytics.summary",
    label: "Analytics Summary",
    category: "metrics",
    description: "Highlights for throughput and performance.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Analytics Summary",
    icon: "✨",
    schema: blockPropSchemas["analytics.summary"],
    defaultProps: {
      cards: [
        { label: "Throughput", value: "2,431", delta: "+4.2%" },
        { label: "Yield", value: "97%", delta: "+1.1%" },
        { label: "Downtime", value: "1.5h", delta: "-0.4h" },
      ],
    },
    controls: ["datasource"],
  },
  "commands.quick": {
    type: "commands.quick",
    label: "Quick Commands",
    category: "system",
    description: "Quick actions palette for demo interactions.",
    defaultSize: { w: 4, h: 4 },
    defaultTitle: "Quick Commands",
    defaultProps: {
      commands: [
        "Show order intake chart",
        "Generate SKU performance table",
        "Highlight overdue items",
      ],
    },
    icon: "⚡",
    schema: blockPropSchemas["commands.quick"],
    controls: [],
  },
  "kanban.simple": {
    type: "kanban.simple",
    label: "Kanban Board",
    category: "system",
    description: "Simple kanban board for stages.",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "Kanban",
    icon: "🗃️",
    schema: blockPropSchemas["table.generic"],
    controls: ["datasource"],
  },
  "capacity.tracker": {
    type: "capacity.tracker",
    label: "Capacity Tracker",
    category: "metrics",
    description: "Team capacity vs usage.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Capacity",
    icon: "📊",
    schema: blockPropSchemas["capacity.tracker"],
    defaultProps: {
      totalCapacity: 100,
      usedCapacity: 78,
      availableCapacity: 22,
      teams: [
        { name: "Engineering", capacity: 40, used: 35, color: "bg-blue-500" },
        { name: "Design", capacity: 25, used: 20, color: "bg-purple-500" },
      ],
      overallUtilization: 78,
    },
    controls: ["datasource"],
  },
  "notifications.panel": {
    type: "notifications.panel",
    label: "Notifications",
    category: "system",
    description: "Alerts and notices.",
    defaultSize: { w: 3, h: 6 },
    defaultTitle: "Notifications",
    icon: "🔔",
    schema: blockPropSchemas["notifications.panel"],
    defaultProps: {
      notifications: [
        { id: "1", title: "Order #1234 ready", body: "QA complete", time: "Just now", status: "info" },
        { id: "2", title: "Line 2 delay", body: "Awaiting materials", time: "5m", status: "warning" },
      ],
    },
    controls: ["datasource"],
  },
  "materials.usage": {
    type: "materials.usage",
    label: "Materials Usage",
    category: "materials",
    description: "Runout projections and at-risk items.",
    defaultSize: { w: 6, h: 10 },
    defaultTitle: "Usage & Runout",
    icon: "🏭",
    schema: blockPropSchemas["materials.usage"],
    defaultProps: {
      currentStock: 1240,
      dailyUsage: 180,
      projectedRunoutDays: 7,
      categories: [
        { name: "Fabric", stock: 540, dailyUsage: 80 },
        { name: "Thread", stock: 320, dailyUsage: 45 },
      ],
      atRisk: [
        { name: "Buttons", stock: 120, dailyUsage: 25, runoutDays: 5 },
      ],
    },
    controls: ["datasource"],
  },
  "materials.inbound.week": {
    type: "materials.inbound.week",
    label: "Inbound Week",
    category: "materials",
    description: "Weekly inbound delivery schedule.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Inbound Week",
    icon: "🚚",
    schema: blockPropSchemas["materials.inbound.week"],
    defaultProps: {
      deliveries: [
        { date: "2025-01-22", po: "PO-4821", supplier: "North Mills", category: "Fabric", items: 120, status: "confirmed" },
        { date: "2025-01-23", po: "PO-4822", supplier: "Allied", category: "Thread", items: 80, status: "pending" },
      ],
    },
    controls: ["datasource"],
  },
  "materials.overdue": {
    type: "materials.overdue",
    label: "Overdue Shipments",
    category: "materials",
    description: "Late purchase orders.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Overdue Shipments",
    icon: "⏰",
    schema: blockPropSchemas["materials.overdue"],
    defaultProps: {
      items: [
        { po: "PO-4711", supplier: "Evergreen Textiles", category: "Fabric", eta: "2025-01-18", daysOverdue: 3 },
      ],
    },
    controls: ["datasource"],
  },
  "materials.supplier.leadtime": {
    type: "materials.supplier.leadtime",
    label: "Supplier Lead Times",
    category: "materials",
    description: "Supplier performance overview.",
    defaultSize: { w: 4, h: 8 },
    defaultTitle: "Supplier Performance",
    icon: "🔗",
    schema: blockPropSchemas["materials.supplier.leadtime"],
    defaultProps: {
      suppliers: [
        { name: "North Mills", avgDays: 7, onTimeRate: 0.92 },
        { name: "Allied", avgDays: 5, onTimeRate: 0.88 },
      ],
    },
    controls: ["datasource"],
  },
  tabs: {
    type: "tabs",
    label: "Tabbed Container",
    category: "system",
    description: "Switch between multiple embedded blocks.",
    defaultSize: { w: 6, h: 6 },
    defaultTitle: "Tabs",
    defaultProps: {
      defaultTab: "overview",
      tabs: [
        { id: "overview", label: "Overview", content: "Use tabs to nest related blocks." },
        { id: "details", label: "Details", content: "Tab content placeholder." },
        { id: "settings", label: "Settings", content: "Configure block-level options here." },
      ],
    },
    icon: "📑",
    schema: blockPropSchemas.tabs,
    controls: [],
  },
  "filter.items": {
    type: "filter.items",
    label: "Items Filter",
    category: "system",
    description: "Filter controls for shared pages.",
    defaultSize: { w: 3, h: 6 },
    defaultTitle: "Filters",
    icon: "🔎",
    schema: blockPropSchemas.note,
    controls: ["datasource"],
  },
  "nav.breadcrumbs": {
    type: "nav.breadcrumbs",
    label: "Breadcrumbs",
    category: "navigation",
    description: "Hierarchical navigation breadcrumbs.",
    defaultSize: { w: 6, h: 3 },
    defaultTitle: "Breadcrumbs",
    defaultProps: {
      items: [
        { id: "1", label: "Dashboard", href: "/" },
        { id: "2", label: "Orders", href: "/orders" },
        { id: "3", label: "Order #1234", isActive: true }
      ],
      showHome: true,
      separator: "chevron"
    },
    icon: "🏠",
    schema: blockPropSchemas["nav.breadcrumbs"],
    controls: ["datasource"],
  },
  "nav.quicksearch": {
    type: "nav.quicksearch",
    label: "Quick Search",
    category: "navigation",
    description: "Search input with recent searches and results.",
    defaultSize: { w: 4, h: 6 },
    defaultTitle: "Quick Search",
    defaultProps: {
      placeholder: "Search orders, items, customers...",
      recentSearches: ["Order #1234", "Acme Denim", "Pending items"],
      showRecent: true
    },
    icon: "🔍",
    schema: blockPropSchemas["nav.quicksearch"],
    controls: ["datasource"],
  },
  "filter.panel": {
    type: "filter.panel",
    label: "Filter Panel",
    category: "navigation",
    description: "Advanced filtering controls with multiple criteria.",
    defaultSize: { w: 3, h: 8 },
    defaultTitle: "Filters",
    defaultProps: {
      groups: [
        {
          id: "status",
          label: "Status",
          type: "multiselect",
          options: [
            { id: "active", label: "Active", count: 12 },
            { id: "pending", label: "Pending", count: 5 },
            { id: "completed", label: "Completed", count: 23 }
          ]
        }
      ],
      showClearAll: true
    },
    icon: "⚙️",
    schema: blockPropSchemas["filter.panel"],
    controls: ["datasource"],
  },
  "toolbar.actions": {
    type: "toolbar.actions",
    label: "Action Toolbar",
    category: "navigation",
    description: "Collection of action buttons and controls.",
    defaultSize: { w: 6, h: 4 },
    defaultTitle: "Actions",
    defaultProps: {
      actions: [
        { id: "1", label: "Create New", icon: "plus", variant: "primary", size: "md" },
        { id: "2", label: "Export", icon: "download", variant: "outline", size: "md" },
        { id: "3", label: "Refresh", icon: "refresh", variant: "ghost", size: "md" }
      ],
      layout: "horizontal",
      showLabels: true
    },
    icon: "🔧",
    schema: blockPropSchemas["toolbar.actions"],
    controls: ["datasource"],
  },
  "status.badges": {
    type: "status.badges",
    label: "Status Badges",
    category: "navigation",
    description: "Status indicators with counts and trends.",
    defaultSize: { w: 4, h: 5 },
    defaultTitle: "Status Overview",
    defaultProps: {
      badges: [
        { id: "1", label: "Active", status: "active", count: 23, trend: "up" },
        { id: "2", label: "Pending", status: "pending", count: 8, trend: "stable" },
        { id: "3", label: "Issues", status: "warning", count: 3, trend: "down" }
      ],
      layout: "grid",
      showCounts: true,
      showTrends: true
    },
    icon: "🏷️",
    schema: blockPropSchemas["status.badges"],
    controls: ["datasource"],
  },
  "form.builder": {
    type: "form.builder",
    label: "Form Builder",
    category: "forms",
    defaultSize: { w: 6, h: 8 },
    defaultTitle: "New Form",
    defaultProps: {
      description: "Fill out this form to submit your information.",
      submitLabel: "Submit",
      isMultiStep: false,
      elements: [],
    },
    icon: "📝",
    schema: blockPropSchemas["form.builder"],
    controls: [],
    slots: [
      {
        id: "element-0",
        label: "Form Element",
        description: "Add an input, section, or control to the form",
        allowedCategories: ["forms"],
      },
    ],
  },
  "form.input": {
    type: "form.input",
    label: "Text Input",
    category: "forms",
    defaultSize: { w: 3, h: 2 },
    defaultTitle: "Text Input",
    defaultProps: {
      label: "Input Label",
      placeholder: "Enter text...",
      type: "text",
      required: false,
      helpText: ""
    },
    icon: "📝",
    schema: blockPropSchemas["form.input"],
    controls: ["datasource"],
  },
  "form.select": {
    type: "form.select",
    label: "Select Dropdown",
    category: "forms",
    defaultSize: { w: 3, h: 2 },
    defaultTitle: "Select Input",
    defaultProps: {
      label: "Select Option",
      placeholder: "Choose an option...",
      required: false,
      options: ["Option 1", "Option 2", "Option 3"],
      multiple: false
    },
    icon: "📋",
    schema: blockPropSchemas["form.select"],
    controls: ["datasource"],
  },
  "form.textarea": {
    type: "form.textarea",
    label: "Text Area",
    category: "forms",
    defaultSize: { w: 4, h: 3 },
    defaultTitle: "Text Area",
    defaultProps: {
      label: "Description",
      placeholder: "Enter details...",
      required: false,
      rows: 3,
      helpText: ""
    },
    icon: "📄",
    schema: blockPropSchemas["form.textarea"],
    controls: ["datasource"],
  },
  "form.checkbox": {
    type: "form.checkbox",
    label: "Checkbox",
    category: "forms",
    defaultSize: { w: 3, h: 2 },
    defaultTitle: "Checkbox",
    defaultProps: {
      label: "Check this option",
      required: false,
      checked: false,
      type: "single"
    },
    icon: "☑️",
    schema: blockPropSchemas["form.checkbox"],
    controls: ["datasource"],
  },
  "form.upload": {
    type: "form.upload",
    label: "File Upload",
    category: "forms",
    defaultSize: { w: 4, h: 4 },
    defaultTitle: "File Upload",
    defaultProps: {
      label: "Upload Files",
      required: false,
      helpText: "Drag and drop files here or click to browse",
      accept: "*/*",
      multiple: false,
      maxSize: 10,
      maxFiles: 1
    },
    icon: "📁",
    schema: blockPropSchemas["form.upload"],
    controls: ["datasource"],
  },
  "form.section": {
    type: "form.section",
    label: "Form Section",
    category: "forms",
    defaultSize: { w: 6, h: 1 },
    defaultTitle: "Section",
    defaultProps: {
      heading: "Section Title",
      description: "This is a section to organize your form",
      divider: true,
      spacing: "md"
    },
    icon: "📑",
    schema: blockPropSchemas["form.section"],
    controls: ["datasource"],
  },
}
